name = "rasty-lib"
main = "./build/server/index.js"
compatibility_date = "2026-01-01"
[[ d1_databases ]]
binding = "DB"
database_name = "rasty-lib-db"
database_id = "eb9d9283-b28d-4564-9067-0122d2e9d357"
migrations_dir = "drizzle"