// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/analytics": {
    params: {};
  };
  "/dashboard/links/new": {
    params: {};
  };
  "/dashboard/links/:linkId/edit": {
    params: {
      "linkId": string;
    };
  };
  "/dashboard/links/:linkId/delete": {
    params: {
      "linkId": string;
    };
  };
  "/:username": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/dashboard" | "/dashboard/settings" | "/dashboard/analytics" | "/dashboard/links/new" | "/dashboard/links/:linkId/edit" | "/dashboard/links/:linkId/delete" | "/:username";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
  "routes/dashboard.analytics.tsx": {
    id: "routes/dashboard.analytics";
    page: "/dashboard/analytics";
  };
  "routes/dashboard.links.new.tsx": {
    id: "routes/dashboard.links.new";
    page: "/dashboard/links/new";
  };
  "routes/dashboard.links.$linkId.edit.tsx": {
    id: "routes/dashboard.links.$linkId.edit";
    page: "/dashboard/links/:linkId/edit";
  };
  "routes/dashboard.links.$linkId.delete.tsx": {
    id: "routes/dashboard.links.$linkId.delete";
    page: "/dashboard/links/:linkId/delete";
  };
  "routes/$username.tsx": {
    id: "routes/$username";
    page: "/:username";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/sign-in": typeof import("./app/routes/sign-in.tsx");
  "routes/sign-up": typeof import("./app/routes/sign-up.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/dashboard.analytics": typeof import("./app/routes/dashboard.analytics.tsx");
  "routes/dashboard.links.new": typeof import("./app/routes/dashboard.links.new.tsx");
  "routes/dashboard.links.$linkId.edit": typeof import("./app/routes/dashboard.links.$linkId.edit.tsx");
  "routes/dashboard.links.$linkId.delete": typeof import("./app/routes/dashboard.links.$linkId.delete.tsx");
  "routes/$username": typeof import("./app/routes/$username.tsx");
};