// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/:username": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/dashboard" | "/:username";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/$username.tsx": {
    id: "routes/$username";
    page: "/:username";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/sign-in": typeof import("./app/routes/sign-in.tsx");
  "routes/sign-up": typeof import("./app/routes/sign-up.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/$username": typeof import("./app/routes/$username.tsx");
};